Add profile management
vjousse/lucky-realworld-example-app pull request #2
Opened 2020-09-26 18:59 UTC by vjousse

2020-09-26 19:39 UTC, JadeKharats requested changes

2020-09-26 19:39 UTC, JadeKharats commented on db/migrations/20200926141022_create_follow.cr
> +
maybe add a SQL CONTRAINT but i never try it
```suggestion
  execute <<-SQL
  ALTER TABLE Follow ADD CONSTRAINT follow UNIQUE (follower, following);  
  SQL
```

2020-09-26 19:39 UTC, JadeKharats commented on src/actions/api/profiles/show.cr
> +    json ProfileSerializer.new(user, follow)
I am in doubt. By reflex, i would have put this business logic in the model.

by example.
```crystal
def follow?(follower) 
  followers.include?(follower)
end
```




and replace by 
```suggestion
    json ProfileSerializer.new(user, current_user.follow?(user)
```

2020-09-27 14:52 UTC, vjousse commented on db/migrations/20200926141022_create_follow.cr
> +
Good catch, i'll add the constraint :+1:

2020-09-27 14:54 UTC, vjousse commented on src/actions/api/profiles/show.cr
> +    json ProfileSerializer.new(user, follow)
I see your point here, but i don't want to grab all the followers with a big sql query to just check for one follower (because I suppose that it's what accessing the followers field will do). That's why I'm doing an sql query here.
And I'm not used to put SQL queries in models. Maybe it would be better suited in an operation or query object?

2020-09-27 19:01 UTC, JadeKharats commented on src/actions/api/profiles/show.cr
> +    json ProfileSerializer.new(user, follow)
yes, indeed, it is not terrible to put the SQL in the model. Adding a method to the query is probably the cleanest solution. My starting point was to replace the "if" structure with something meaningful. With the method in a query, we should solve this point.

2020-09-28 19:23 UTC, vjousse commented on src/actions/api/profiles/show.cr
> +    json ProfileSerializer.new(user, follow)
I've pushed a new commit with the code moved in the query class :+1:

2020-09-30 09:09 UTC, merged